first_number = int(input("Enter first number: "))
second_number = int(input("Enter second number: "))
print("Addition: ", first_number + second_number)
print("Subtraction: ", first_number - second_number)
print("Multiplication: ", first_number * second_number)
print("Division: ", first_number / second_number)